import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Topbar from "@/Components/header/Topbar"; 


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-gradient-to-br from-[#00160d] to-slate-950 relative`}
      >
        <div className="relative bg-gradient-to-br from-[#08f5e5]/2 to-slate-950/2 backdrop-blur-lg z-20">
            <Topbar />  
        {children}
        </div>
      
        
      </body>
    </html>
  );
}
